## Numpy Assignment

### Task1

Write a function so that the columns of the output matrix are powers of the input vector. The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1. HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde

## AlexandreTheophile Vandermonde Matrix


In [1]:
import numpy as np

In [5]:
# Taking input from user
vector = np.array(list(map(int,input("Enter the elements of a Vector : ").split())))

Enter the elements of a Vector : 1 2 3


In [7]:
# Displaying the vector with its type
vector , type(vector)

(array([1, 2, 3]), numpy.ndarray)

In [8]:
#Making Vandermonde Matrix using numpy 
result = np.vander(vector, increasing=True)

In [9]:
result

array([[1, 1, 1],
       [1, 2, 4],
       [1, 3, 9]])

In [10]:
# Example 2
vector = np.array(list(map(int,input("Enter the elements of a Vector : ").split())))
result = np.vander(vector, increasing=True)
print(result)

Enter the elements of a Vector : 1 1 1 1
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [11]:
# Example 3
vector = np.array(list(map(int,input("Enter the elements of a Vector : ").split())))
result = np.vander(vector, increasing=True)
print(result)

Enter the elements of a Vector : 1 2 3 4 5
[[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]]


## Task 2

<b>Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows: The moving average sequence has n-k+1 elements as shown below.</b>

### Moving Average of n values with K>0 As window size


In [12]:
n = int(input("Enter the Number of elements : "))
arr = np.array(list(map(int,input("Enter the n elements : ").split())))
k = int(input("Enter the window size : "))

Enter the Number of elements : 10
Enter the n elements : 10 20 30 40 50 60 70 80 90 100
Enter the window size : 4


In [13]:
sm = np.cumsum(arr,dtype = float)

In [22]:
print("Moving Average's are : ")
for i in range(len(arr)-k+1):
    avg = np.sum(arr[i:i+k],dtype=float)/k
    print(np.round(avg,2),end = "  ")

Moving Average's are : 
25.0  35.0  45.0  55.0  65.0  75.0  85.0  

In [23]:
## Sample input given in Assignment
n = 13
arr = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
k = 3

In [24]:
print("Moving Average's are : ")
for i in range(len(arr)-k+1):
    avg = np.sum(arr[i:i+k],dtype=float)/k
    print(np.round(avg,2),end = "  ")

Moving Average's are : 
5.0  4.67  5.67  6.67  9.67  28.67  49.33  72.67  84.0  93.33  116.33  